services:
  - type: web
    name: elisi-fxey
    runtime: node
    rootDir: server
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
